jwt.secret=8ZrVt3pQmK7dW2xN9sL4hJ6cF0yAqE1uG5bT8nX3vP7kR2mS

server.port=8080

# R2DBC H2 en memoria (NO Postgres)
spring.r2dbc.url=r2dbc:h2:mem:///securedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

# Inicializar schema.sql al arrancar
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Logs (opcional)
logging.level.org.springframework.security=INFO

# JWT (puedes cambiarlo por variables de entorno si quieres)
app.jwt.secret=CHANGE_ME_CHANGE_ME_CHANGE_ME_CHANGE_ME_32bytes_min
app.jwt.expMinutes=60

